/**
 * Created by elizabethdudley on 11/16/16.
 */
public enum Directions {
    NORTH, EAST, WEST, SOUTH, NORTHEAST, NORTHWEST, SOUTHEAST, SOUTHWEST, NORTHISH, EASTISH, SOUTHISH, WESTISH,
    NORTHEASTISH, NORTHWESTISH, SOUTHEASTISH, SOUTHWESTISH
}
